version: "3"
services:
  # app:
  #   build: .
  #   command: npm start
  #   volumes:
  #     - ./app:/usr/src/app
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
