name: Node.js CI

on: [push]

jobs:
  scheduler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: "14.4.0"
      - run: |
          npm install
          npm run lint
          npm test
